class AddArticles < ActiveRecord::Migration[7.1]
  def up

      Article.create(title: "Read", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Move", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Relate", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Observe", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Turn", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Write", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Create", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Change", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Rest", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Share", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Develop", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Dream", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Understand", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Less", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Matter", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")

      Article.create(title: "Write", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Story", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Impact", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Rest", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Free", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Reflect", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Respond", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Connect", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Give", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Live", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Pause", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Difference", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Time", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "People", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "World", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")

      Article.create(title: "Inform", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Forget", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Remember", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Story", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Love", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Art", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Wonder", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Explore", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Pen", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Live", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Collect", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Think", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Defy", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Comfort", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Reason", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")

      Article.create(title: "Travel", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Journal", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Quest", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Intrigue", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Suspense", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Kindness", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "Paper", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Ackonwledge", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Pen", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Defend", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")
      Article.create(title: "Collect", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nisi libero, laoreet sed malesuada non, tincidunt ac ex. Nunc a ante sit amet lacus vehicula hendrerit. Suspendisse pretium feugiat massa, at accumsan enim dictum in. Suspendisse lectus nisl, fermentum sit amet dolor in, sagittis sagittis tortor.")
      Article.create(title: "History", text: "Suspendisse potenti. Duis varius, justo sed posuere egestas, odio justo egestas mi, vitae tincidunt quam enim sed odio. Vestibulum sit amet viverra nulla..")
      Article.create(title: "Defy", text: "Sed egestas velit nisl, nec viverra est faucibus convallis. Aliquam et posuere nisl, ut malesuada mi. Sed ac neque et lorem aliquam imperdiet vitae a quam. Donec interdum enim et hendrerit mollis. Vestibulum laoreet varius turpis vel tempus. ")
      Article.create(title: "Imagine", text: "Proin pellentesque imperdiet imperdiet. Curabitur finibus, orci a ultrices dictum, leo nisi sodales tellus, vitae malesuada sapien massa eget lectus. Integer a lorem nisi.")
      Article.create(title: "Write", text: "Etiam tempor finibus consequat. Integer sit amet magna imperdiet, iaculis mauris at, malesuada erat. Phasellus neque lorem, dignissim quis vestibulum in, pretium congue diam.")


  end

  def down
    Article.delete_all
  end
end
